### ISSUE TITLE
Not able to stop the Telebot

### ISSUE THREAD

**Issue by atishaye** [atishaye/TeleCrick#1]
https://github.com/atishaye/TeleCrick/blob/f4e3a6438a9619cc2b588060da46012df31e0ef0/get_live_score.py#L21-L36
I am trying to break from the while loop whenever the user enters "/stop" in Telegram. While inside the loop, to read the latest message, I tried to use the getUpdates method but it always returns a blank list. So for now, I am using an arbitrary command that returns an error and exits the program.

**Comment by noturshek** [comment]
Have you tried using the break statement?

**Comment by atishaye** [comment]
> Have you tried using the break statement?

Let me explain what I was trying to do
Inside the loop, I was checking if the user enters the "/stop" command by using the getUpdates method and storing the result in a boolean variable(flag). Finally, if the flag is true, I'll break from the loop. Now, as I have already stated my problem above, the getUpdates method is always returning an empty list.
